workflows:
  android-build:
    name: Nextime 3D Android Build
    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Set up permissions
        script: chmod +x gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

      - name: Build Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/release/*.apk

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
        notify:
          success: true
          failure: true
