workflows:
  android-debug:
    name: Nextime 3D Debug APK

    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Grant execute permission
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace --no-daemon

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
        notify:
          success: true
          failure: true
